version: '3.9'

services:
  api:
    build: .
    command: >
      sh -c "python /waitlist/wait_for_postgres.py &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - api.env
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - posts-db:/var/lib/postgresql/data

volumes:
  posts-db: